name: CI - Django Polls App

on:
  push:
  pull_request:

jobs:
  build:
    name: ðŸ—ï¸ Build
    runs-on: ubuntu-latest

    outputs:
      build-ok: true

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer dÃ©pendances Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: VÃ©rification versions
        run: |
          python --version
          pip list

  ruff:
    name: ðŸŒª Ruff
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer Ruff
        run: |
          pip install ruff

      - name: Lancer Ruff
        run: |
          echo "Lancement de Ruff..."
          ruff check .

  pylint:
    name: ðŸ” Pylint (min 7/10)
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer dÃ©pendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lancer Pylint + extraction score
        run: |
          echo "ExÃ©cution de Pylint..."
          pylint *.py > pylint_output.txt || true

          echo "==== RÃ©sultat Pylint ===="
          cat pylint_output.txt

          SCORE=$(grep -oP "(?<=rated at )[\d\.]+" pylint_output.txt || echo "0")
          echo "Score pylint dÃ©tectÃ© : $SCORE / 10"

          python3 - <<EOF
          score = float("$SCORE")
          if score < 7:
              print("âŒ Score Pylint insuffisant (<7/10). Ã‰chec du job.")
              exit(1)
          else:
              print("âœ… Score Pylint suffisant.")
          EOF

  tests:
    name: ðŸ§ª Tests Django
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer dÃ©pendances
        run: |
          pip install -r requirements.txt

      - name: Lancer tests Django
        run: |
          python manage.py migrate --noinput
          python manage.py test

  docker:
    name: ðŸ³ Docker Build & Push ECR
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-region: eu-north-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      # Login
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 \
          | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com

      # Build image
      - name: Build Docker image
        run: |
          docker build -t django-polls .

      # Tag image
      - name: Tag Docker image for ECR
        run: |
          docker tag django-polls:latest \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com/django-polls:latest

      # Push image
      - name: Push Docker image to ECR
        run: |
          docker push \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com/django-polls:latest
